/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description List disaster events with filtering and pagination.
         *
         *     Args:
         *         event_service: Injected EventService instance
         *         types: Filter by event types (earthquake, flood, etc.)
         *         severities: Filter by severity levels (low, medium, high, critical)
         *         start_date: Filter events starting from this date
         *         end_date: Filter events up to this date
         *         min_lng: Bounding box minimum longitude
         *         min_lat: Bounding box minimum latitude
         *         max_lng: Bounding box maximum longitude
         *         max_lat: Bounding box maximum latitude
         *         center_lat: Center latitude for radius search (-90 to 90)
         *         center_lng: Center longitude for radius search (-180 to 180)
         *         radius_km: Search radius in km (max 500km)
         *         is_active: Filter by active status
         *         limit: Maximum number of events to return (default 50, max 200)
         *         offset: Number of events to skip for pagination
         *
         *     Returns:
         *         EventListResponse with paginated event data
         */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Get detailed information for a specific event.
         *
         *     Args:
         *         event_id: UUID of the event to retrieve
         *         event_service: Injected EventService instance
         *
         *     Returns:
         *         EventDetailResponse with full event details
         *
         *     Raises:
         *         HTTPException: 404 if event not found
         */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Layers
         * @description Get geographic layers for a specific event.
         *
         *     Args:
         *         event_id: UUID of the event
         *         event_service: Injected EventService instance
         *
         *     Returns:
         *         Dictionary with layers list (currently empty in Phase 2)
         */
        get: operations["get_event_layers_api_v1_events__event_id__layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/tiles/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vector Tile */
        get: operations["get_vector_tile_api_v1_geodata_tiles__z___x___y__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/events/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Clusters */
        get: operations["get_event_clusters_api_v1_geodata_events_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/events/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events Geojson */
        get: operations["get_events_geojson_api_v1_geodata_events_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/gdacs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Gdacs
         * @description Sync GDACS events and store to database.
         *
         *     Fetches events from GDACS RSS feed and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_gdacs_api_v1_sync_gdacs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/copernicus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Copernicus
         * @description Sync Copernicus EMS events and store to database.
         *
         *     Fetches activations from Copernicus EMS API and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_copernicus_api_v1_sync_copernicus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/usgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Usgs
         * @description Sync USGS earthquake data and store to database.
         *
         *     Fetches earthquake events from USGS GeoJSON feed and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Args:
         *         feed: USGS feed identifier. Available options:
         *             - 4.5_day: M4.5+ earthquakes from the past day
         *             - 4.5_week: M4.5+ earthquakes from the past week (default)
         *             - all_day: All earthquakes from the past day
         *             - significant_month: Significant earthquakes from the past month
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_usgs_api_v1_sync_usgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/eonet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Eonet
         * @description Sync NASA EONET events and store to database.
         *
         *     Fetches natural event data from NASA EONET API and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Args:
         *         status: Event status filter:
         *             - open: Only ongoing events (default)
         *             - closed: Only closed/ended events
         *             - all: Both open and closed events
         *         days: Fetch events from the last N days (default: 30)
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_eonet_api_v1_sync_eonet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Status
         * @description Get overall system status.
         */
        get: operations["admin_status_api_v1_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dedup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dedup Status
         * @description Get deduplication statistics.
         */
        get: operations["dedup_status_api_v1_admin_dedup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sync/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Manually trigger data synchronization.
         *
         *     Args:
         *         source: Optional source name (gdacs, usgs, eonet, copernicus).
         *                 If not provided, syncs all sources.
         */
        post: operations["trigger_sync_api_v1_admin_sync_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/merge/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Offline Merge
         * @description Trigger offline merge job to deduplicate existing events.
         *
         *     This runs the merge job in the background. Use dry_run=true (default)
         *     to preview changes before applying them.
         */
        post: operations["trigger_offline_merge_api_v1_admin_merge_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/merge/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Merge Status
         * @description Get merge statistics and status.
         */
        get: operations["get_merge_status_api_v1_admin_merge_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduler Status */
        get: operations["scheduler_status_scheduler_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClusterBBox */
        ClusterBBox: {
            /** Min Lat */
            min_lat: number;
            /** Max Lat */
            max_lat: number;
            /** Min Lng */
            min_lng: number;
            /** Max Lng */
            max_lng: number;
        };
        /** ClusterResponse */
        ClusterResponse: {
            /** Zoom */
            zoom: number;
            /** Clusters */
            clusters: components["schemas"]["EventCluster"][];
            /** Unclustered */
            unclustered: components["schemas"]["EventResponse"][];
            /** Total Events */
            total_events: number;
            /** Total Clusters */
            total_clusters: number;
        };
        /** DataSourceRef */
        DataSourceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Name */
            name: string;
            /** Type */
            type?: string | null;
            /** Url */
            url?: string | null;
            /** License */
            license?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DisplayPoint
         * @description UI 표시용 좌표 (실제 좌표 또는 admin_area centroid).
         */
        DisplayPoint: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Source
             * @enum {string}
             */
            source: "event" | "admin_centroid" | "country_centroid";
        };
        /** EventCluster */
        EventCluster: {
            /** Cluster Id */
            cluster_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Count */
            count: number;
            bbox?: components["schemas"]["ClusterBBox"] | null;
            /** Event Types */
            event_types: {
                [key: string]: number;
            };
            /** Max Severity */
            max_severity?: string | null;
        };
        /** EventDetailResponse */
        EventDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location: components["schemas"]["Location"];
            /** Geo Precision */
            geo_precision?: string | null;
            display_point?: components["schemas"]["DisplayPoint"] | null;
            /** Severity */
            severity: string;
            /** Affected Population */
            affected_population?: number | null;
            /** Affected Area Km2 */
            affected_area_km2?: number | null;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Sources */
            sources: components["schemas"]["DataSourceRef"][];
            geometry?: components["schemas"]["GeoJSONGeometry"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Layers
             * @default []
             */
            layers: components["schemas"]["GeoLayerResponse"][];
            /**
             * Datasets
             * @default []
             */
            datasets: components["schemas"]["DatasetResponse"][];
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["EventMetricResponse"][];
        };
        /** EventListResponse */
        EventListResponse: {
            /** Data */
            data: components["schemas"]["EventResponse"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** EventMetricResponse */
        EventMetricResponse: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Metric Type */
            metric_type: string;
            /** Value */
            value: number;
        };
        /** EventResponse */
        EventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location: components["schemas"]["Location"];
            /** Geo Precision */
            geo_precision?: string | null;
            display_point?: components["schemas"]["DisplayPoint"] | null;
            /** Severity */
            severity: string;
            /** Affected Population */
            affected_population?: number | null;
            /** Affected Area Km2 */
            affected_area_km2?: number | null;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Sources */
            sources: components["schemas"]["DataSourceRef"][];
            geometry?: components["schemas"]["GeoJSONGeometry"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "earthquake" | "flood" | "wildfire" | "hurricane" | "tsunami" | "volcano" | "war" | "pollution" | "drought" | "other" | "landslide" | "industrial" | "epidemic" | "storm" | "coldwave" | "heatwave" | "complex_emergency";
        /** GeoJSONFeature */
        GeoJSONFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            } | null;
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        };
        /** GeoJSONFeatureCollection */
        GeoJSONFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["GeoJSONFeature"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** GeoJSONGeometry */
        GeoJSONGeometry: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: unknown[];
        };
        /** GeoLayerResponse */
        GeoLayerResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Layer Type */
            layer_type: string;
            geometry: components["schemas"]["GeoJSONGeometry"];
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Location
         * @description Geographic location with optional coordinates and region info.
         */
        Location: {
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Region */
            region?: string | null;
        };
        /** MergeJobResponse */
        MergeJobResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** Pagination */
        Pagination: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * SeverityLevel
         * @enum {string}
         */
        SeverityLevel: "low" | "medium" | "high" | "critical";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                q?: string | null;
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                start_date?: string | null;
                end_date?: string | null;
                min_lng?: number | null;
                min_lat?: number | null;
                max_lng?: number | null;
                max_lat?: number | null;
                center_lat?: number | null;
                center_lng?: number | null;
                radius_km?: number | null;
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_layers_api_v1_events__event_id__layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vector_tile_api_v1_geodata_tiles__z___x___y__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_clusters_api_v1_geodata_events_clusters_get: {
        parameters: {
            query: {
                /** @description Map zoom level (0-20) */
                zoom: number;
                min_lat?: number | null;
                max_lat?: number | null;
                min_lng?: number | null;
                max_lng?: number | null;
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_geojson_api_v1_geodata_events_geojson_get: {
        parameters: {
            query?: {
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                start_date?: string | null;
                end_date?: string | null;
                min_lng?: number | null;
                min_lat?: number | null;
                max_lng?: number | null;
                max_lat?: number | null;
                is_active?: boolean | null;
                include_properties?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_gdacs_api_v1_sync_gdacs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_copernicus_api_v1_sync_copernicus_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_usgs_api_v1_sync_usgs_post: {
        parameters: {
            query?: {
                /** @description USGS feed to sync. Options: 4.5_day, 4.5_week, all_day, significant_month */
                feed?: "4.5_day" | "4.5_week" | "all_day" | "significant_month";
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_eonet_api_v1_sync_eonet_post: {
        parameters: {
            query?: {
                /** @description Event status filter. Options: open, closed, all */
                status?: "open" | "closed" | "all";
                /** @description Fetch events from the last N days */
                days?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_status_api_v1_admin_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dedup_status_api_v1_admin_dedup_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_v1_admin_sync_trigger_post: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_offline_merge_api_v1_admin_merge_trigger_post: {
        parameters: {
            query?: {
                /** @description Preview without making changes */
                dry_run?: boolean;
                /** @description Scope: all, active, or inactive */
                scope?: string;
                /** @description Process events since date (ISO format) */
                since?: string | null;
                /** @description Comma-separated event types */
                types?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_merge_status_api_v1_admin_merge_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    scheduler_status_scheduler_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
