/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description List disaster events with filtering and pagination.
         *
         *     Args:
         *         event_service: Injected EventService instance
         *         types: Filter by event types (earthquake, flood, etc.)
         *         severities: Filter by severity levels (low, medium, high, critical)
         *         start_date: Filter events starting from this date
         *         end_date: Filter events up to this date
         *         min_lng: Bounding box minimum longitude
         *         min_lat: Bounding box minimum latitude
         *         max_lng: Bounding box maximum longitude
         *         max_lat: Bounding box maximum latitude
         *         center_lat: Center latitude for radius search (-90 to 90)
         *         center_lng: Center longitude for radius search (-180 to 180)
         *         radius_km: Search radius in km (max 500km)
         *         is_active: Filter by active status
         *         limit: Maximum number of events to return (default 50, max 200)
         *         offset: Number of events to skip for pagination
         *
         *     Returns:
         *         EventListResponse with paginated event data
         */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Timeline
         * @description Event onsets per time bucket (by type) for the timeline histogram.
         *
         *     Declared before /{event_id} so "timeline" is not parsed as a UUID.
         */
        get: operations["event_timeline_api_v1_events_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Get detailed information for a specific event.
         *
         *     Args:
         *         event_id: UUID of the event to retrieve
         *         event_service: Injected EventService instance
         *
         *     Returns:
         *         EventDetailResponse with full event details
         *
         *     Raises:
         *         HTTPException: 404 if event not found
         */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Layers
         * @description Get geographic layers for a specific event.
         *
         *     Args:
         *         event_id: UUID of the event
         *         event_service: Injected EventService instance
         *
         *     Returns:
         *         Dictionary with layers list (currently empty in Phase 2)
         */
        get: operations["get_event_layers_api_v1_events__event_id__layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/tiles/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vector Tile */
        get: operations["get_vector_tile_api_v1_geodata_tiles__z___x___y__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/events/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Clusters */
        get: operations["get_event_clusters_api_v1_geodata_events_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/events/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events Geojson */
        get: operations["get_events_geojson_api_v1_geodata_events_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get View Summary
         * @description Totals for the current map view (omit the bbox for the whole world).
         */
        get: operations["get_view_summary_api_v1_geodata_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geodata/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nearby Events
         * @description Events around a point, nearest first.
         */
        get: operations["get_nearby_events_api_v1_geodata_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/gdacs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Gdacs
         * @description Sync GDACS events and store to database.
         *
         *     Fetches events from GDACS RSS feed and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_gdacs_api_v1_sync_gdacs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/copernicus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Copernicus
         * @description Sync Copernicus EMS events and store to database.
         *
         *     Fetches activations from Copernicus EMS API and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_copernicus_api_v1_sync_copernicus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/usgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Usgs
         * @description Sync USGS earthquake data and store to database.
         *
         *     Fetches earthquake events from USGS GeoJSON feed and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Args:
         *         feed: USGS feed identifier. Available options:
         *             - 4.5_day: M4.5+ earthquakes from the past day
         *             - 4.5_week: M4.5+ earthquakes from the past week (default)
         *             - all_day: All earthquakes from the past day
         *             - significant_month: Significant earthquakes from the past month
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_usgs_api_v1_sync_usgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/eonet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Eonet
         * @description Sync NASA EONET events and store to database.
         *
         *     Fetches natural event data from NASA EONET API and ingests them into the database.
         *     Uses upsert logic to handle duplicates.
         *
         *     Args:
         *         status: Event status filter:
         *             - open: Only ongoing events (default)
         *             - closed: Only closed/ended events
         *             - all: Both open and closed events
         *         days: Fetch events from the last N days (default: 30)
         *
         *     Returns:
         *         Status with created/updated/failed counts
         */
        post: operations["sync_eonet_api_v1_sync_eonet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Status
         * @description Freshness of every active data source, alphabetically.
         */
        get: operations["list_source_status_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards/cyclones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Cyclones
         * @description Active tropical cyclones (NHC basins): forecast cone, track, positions
         *     and past track as GeoJSON. Cached for 10 minutes; `stale` is true when
         *     NOAA is unreachable and the last good data is being served.
         */
        get: operations["active_cyclones_api_v1_hazards_cyclones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards/shakemaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Shakemaps
         * @description Shaking-intensity (MMI IV+) contours for the past week's M4.5+
         *     earthquakes that have a USGS ShakeMap, strongest shaking first.
         *     Cached for 10 minutes; `stale` marks cached data served during an outage.
         */
        get: operations["recent_shakemaps_api_v1_hazards_shakemaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards/fires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Fires
         * @description NASA FIRMS VIIRS active-fire detections in the viewport from the last
         *     `hours`, most intense first (fire radiative power). `truncated` means
         *     zoom in to see smaller fires.
         */
        get: operations["active_fires_api_v1_hazards_fires_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Status */
        get: operations["agent_status_api_v1_agent_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Usage */
        get: operations["agent_usage_api_v1_agent_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Chat */
        post: operations["agent_chat_api_v1_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/satellites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Satellite Positions
         * @description Sub-satellite points of Earth-observation satellites (CelesTrak, SGP4).
         */
        get: operations["satellite_positions_api_v1_tracks_satellites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/satellites/passes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Satellite Passes
         * @description Upcoming passes of Earth-observation satellites over a place, soonest first.
         */
        get: operations["satellite_passes_api_v1_tracks_satellites_passes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/aircraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aircraft Around
         * @description Aircraft (ADS-B, adsb.lol) around a point; privacy-programme aircraft are excluded.
         */
        get: operations["aircraft_around_api_v1_tracks_aircraft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vessels In View
         * @description Ships (AIS) reported in the last 30 min around active high/critical events.
         *
         *     `enabled` is false when the server has no AISStream key (the list is then empty).
         */
        get: operations["vessels_in_view_api_v1_tracks_vessels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cameras In View
         * @description Public traffic cameras in a bbox (GeoJSON).
         */
        get: operations["cameras_in_view_api_v1_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cameras Nearby
         * @description Cameras closest to a point (e.g. an event), nearest first.
         */
        get: operations["cameras_nearby_api_v1_cameras_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Camera Snapshot
         * @description Latest still image of a camera, fetched by the server (never by URL from the client).
         */
        get: operations["camera_snapshot_api_v1_cameras__camera_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/radio/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radio Nearby
         * @description Stations near a point from the Radio Browser directory, most listened first.
         */
        get: operations["radio_nearby_api_v1_radio_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route
         * @description Route between two points with the active hazards it passes (and a detour when possible).
         */
        post: operations["route_api_v1_routing_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Infrastructure In View
         * @description Dams and power plants in the viewport as GeoJSON, most significant
         *     first (MW / dam height). `truncated` means zoom in to see the rest.
         */
        get: operations["infrastructure_in_view_api_v1_infrastructure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Status
         * @description Get overall system status.
         */
        get: operations["admin_status_api_v1_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dedup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dedup Status
         * @description Get deduplication statistics.
         */
        get: operations["dedup_status_api_v1_admin_dedup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sync/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Manually trigger data synchronization.
         *
         *     Args:
         *         source: Optional source name (gdacs, usgs, eonet, copernicus).
         *                 If not provided, syncs all sources.
         */
        post: operations["trigger_sync_api_v1_admin_sync_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/merge/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Offline Merge
         * @description Trigger offline merge job to deduplicate existing events.
         *
         *     This runs the merge job in the background. Use dry_run=true (default)
         *     to preview changes before applying them.
         */
        post: operations["trigger_offline_merge_api_v1_admin_merge_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/merge/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Merge Status
         * @description Get merge statistics and status.
         */
        get: operations["get_merge_status_api_v1_admin_merge_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduler Status */
        get: operations["scheduler_status_scheduler_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentChatRequest */
        AgentChatRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            context?: components["schemas"]["MapContext"];
        };
        /** AgentChatResponse */
        AgentChatResponse: {
            /** Reply */
            reply: string;
            /** Actions */
            actions: (components["schemas"]["FlyTo"] | components["schemas"]["SetLayers"] | components["schemas"]["SetEventFilters"] | components["schemas"]["SetTime"] | components["schemas"]["SelectEvent"] | components["schemas"]["PlayBrief"])[];
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallRecord"][];
            usage: components["schemas"]["AgentUsageInfo"];
        };
        /** AgentStatus */
        AgentStatus: {
            /** Enabled */
            enabled: boolean;
            /** Model */
            model: string | null;
            /** Session Cap */
            session_cap: number;
        };
        /** AgentUsageInfo */
        AgentUsageInfo: {
            /** Session Tokens */
            session_tokens: number;
            /** Session Cap */
            session_cap: number;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ClusterBBox */
        ClusterBBox: {
            /** Min Lat */
            min_lat: number;
            /** Max Lat */
            max_lat: number;
            /** Min Lng */
            min_lng: number;
            /** Max Lng */
            max_lng: number;
        };
        /** ClusterResponse */
        ClusterResponse: {
            /** Zoom */
            zoom: number;
            /** Clusters */
            clusters: components["schemas"]["EventCluster"][];
            /** Unclustered */
            unclustered: components["schemas"]["EventResponse"][];
            /** Total Events */
            total_events: number;
            /** Total Clusters */
            total_clusters: number;
        };
        /** DataSourceRef */
        DataSourceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Name */
            name: string;
            /** Type */
            type?: string | null;
            /** Url */
            url?: string | null;
            /** License */
            license?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DisplayPoint
         * @description UI 표시용 좌표 (실제 좌표 또는 admin_area centroid).
         */
        DisplayPoint: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Source
             * @enum {string}
             */
            source: "event" | "admin_centroid" | "country_centroid";
        };
        /** EventCluster */
        EventCluster: {
            /** Cluster Id */
            cluster_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Count */
            count: number;
            bbox?: components["schemas"]["ClusterBBox"] | null;
            /** Event Types */
            event_types: {
                [key: string]: number;
            };
            /** Max Severity */
            max_severity?: string | null;
        };
        /** EventDetailResponse */
        EventDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location: components["schemas"]["Location"];
            /** Geo Precision */
            geo_precision?: string | null;
            display_point?: components["schemas"]["DisplayPoint"] | null;
            /** Severity */
            severity: string;
            /** Affected Population */
            affected_population?: number | null;
            /** Affected Area Km2 */
            affected_area_km2?: number | null;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Sources */
            sources: components["schemas"]["DataSourceRef"][];
            geometry?: components["schemas"]["GeoJSONGeometry"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Layers
             * @default []
             */
            layers: components["schemas"]["GeoLayerResponse"][];
            /**
             * Datasets
             * @default []
             */
            datasets: components["schemas"]["DatasetResponse"][];
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["EventMetricResponse"][];
        };
        /** EventListResponse */
        EventListResponse: {
            /** Data */
            data: components["schemas"]["EventResponse"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** EventMetricResponse */
        EventMetricResponse: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Metric Type */
            metric_type: string;
            /** Value */
            value: number;
        };
        /** EventResponse */
        EventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location: components["schemas"]["Location"];
            /** Geo Precision */
            geo_precision?: string | null;
            display_point?: components["schemas"]["DisplayPoint"] | null;
            /** Severity */
            severity: string;
            /** Affected Population */
            affected_population?: number | null;
            /** Affected Area Km2 */
            affected_area_km2?: number | null;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Sources */
            sources: components["schemas"]["DataSourceRef"][];
            geometry?: components["schemas"]["GeoJSONGeometry"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "earthquake" | "flood" | "wildfire" | "hurricane" | "tsunami" | "volcano" | "war" | "pollution" | "drought" | "other" | "landslide" | "industrial" | "epidemic" | "storm" | "coldwave" | "heatwave" | "complex_emergency";
        /** FlyTo */
        FlyTo: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fly_to";
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Zoom
             * @default 5
             */
            zoom: number;
        };
        /** GeoJSONFeature */
        GeoJSONFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            } | null;
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        };
        /** GeoJSONFeatureCollection */
        GeoJSONFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["GeoJSONFeature"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** GeoJSONGeometry */
        GeoJSONGeometry: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: unknown[];
        };
        /** GeoLayerResponse */
        GeoLayerResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Layer Type */
            layer_type: string;
            geometry: components["schemas"]["GeoJSONGeometry"];
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Location
         * @description Geographic location with optional coordinates and region info.
         */
        Location: {
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Region */
            region?: string | null;
        };
        /**
         * MapContext
         * @description What the user is looking at, sent with every message for grounding.
         */
        MapContext: {
            /** Bbox */
            bbox?: number[] | null;
            /** Center Lat */
            center_lat?: number | null;
            /** Center Lng */
            center_lng?: number | null;
            /** Zoom */
            zoom?: number | null;
            /** At */
            at?: string | null;
            /** Visible Layers */
            visible_layers?: string[];
            /** Available Layers */
            available_layers?: string[];
            /** Types */
            types?: components["schemas"]["EventType"][] | null;
            /** Severities */
            severities?: components["schemas"]["SeverityLevel"][] | null;
            /** Selected Event Id */
            selected_event_id?: string | null;
        };
        /** MergeJobResponse */
        MergeJobResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** NearbyCamera */
        NearbyCamera: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Direction */
            direction: string | null;
            /** Source */
            source: string;
            /** Distance Km */
            distance_km: number;
        };
        /** NearbyEvent */
        NearbyEvent: {
            event: components["schemas"]["EventResponse"];
            /** Distance Km */
            distance_km: number;
        };
        /** NearbyResponse */
        NearbyResponse: {
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Radius Km */
            radius_km: number;
            /** Data */
            data: components["schemas"]["NearbyEvent"][];
        };
        /** Pagination */
        Pagination: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PlayBrief */
        PlayBrief: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "play_brief";
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
        };
        /** Point */
        Point: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** RadioNearbyResponse */
        RadioNearbyResponse: {
            /** Stations */
            stations: components["schemas"]["RadioStation"][];
        };
        /** RadioStation */
        RadioStation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Stream Url */
            stream_url: string | null;
            /** Listen Url */
            listen_url: string | null;
            /** Homepage */
            homepage: string | null;
            /** Codec */
            codec: string | null;
            /** Bitrate */
            bitrate: number | null;
            /** Country Code */
            country_code: string | null;
            /** Language */
            language: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance Km */
            distance_km: number;
            /** On Air */
            on_air: boolean;
            /** Last Checked */
            last_checked: string | null;
        };
        /** RouteGeometry */
        RouteGeometry: {
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
            /** Coordinates */
            coordinates: number[][];
        };
        /** RouteHazard */
        RouteHazard: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Severity */
            severity: string;
            /** Zone Km */
            zone_km: number;
            /** Distance Km */
            distance_km: number;
        };
        /** RouteRequest */
        RouteRequest: {
            start: components["schemas"]["Point"];
            end: components["schemas"]["Point"];
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "truck" | "pedestrian" | "bicycle";
            /**
             * Avoid Hazards
             * @default true
             */
            avoid_hazards: boolean;
        };
        /** RouteResponse */
        RouteResponse: {
            geometry: components["schemas"]["RouteGeometry"];
            /** Distance Km */
            distance_km: number | null;
            /** Duration Min */
            duration_min: number | null;
            /** Hazards */
            hazards: components["schemas"]["RouteHazard"][];
            /** Fires Near Route */
            fires_near_route: number;
            /** Avoided */
            avoided: boolean;
            /** Avoidance Note */
            avoidance_note: ("router_limit" | "no_detour") | null;
        };
        /** SatellitePass */
        SatellitePass: {
            /** Name */
            name: string;
            /** Norad Id */
            norad_id: number;
            /**
             * Rise
             * Format: date-time
             */
            rise: string;
            /**
             * Culmination
             * Format: date-time
             */
            culmination: string;
            /**
             * Set
             * Format: date-time
             */
            set: string;
            /** Max Elevation Deg */
            max_elevation_deg: number;
            /** Daylight */
            daylight: boolean;
        };
        /** SatellitePassesResponse */
        SatellitePassesResponse: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Hours */
            hours: number;
            /** Min Elevation Deg */
            min_elevation_deg: number;
            /** Passes */
            passes: components["schemas"]["SatellitePass"][];
        };
        /** SelectEvent */
        SelectEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "select_event";
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
        };
        /** SetEventFilters */
        SetEventFilters: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "set_event_filters";
            /** Types */
            types?: components["schemas"]["EventType"][] | null;
            /** Severities */
            severities?: components["schemas"]["SeverityLevel"][] | null;
        };
        /** SetLayers */
        SetLayers: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "set_layers";
            /** Show */
            show?: string[];
            /** Hide */
            hide?: string[];
        };
        /** SetTime */
        SetTime: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "set_time";
            /** At */
            at?: string | null;
        };
        /**
         * SeverityLevel
         * @enum {string}
         */
        SeverityLevel: "low" | "medium" | "high" | "critical";
        /** SourceStatus */
        SourceStatus: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Is Realtime */
            is_realtime: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "stale" | "failing" | "never";
            /** Last Sync */
            last_sync: string | null;
            /** Sync Interval Minutes */
            sync_interval_minutes: number | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Last Error */
            last_error: string | null;
        };
        /** TimelineBucket */
        TimelineBucket: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Total */
            total: number;
            /** By Type */
            by_type: {
                [key: string]: number;
            };
        };
        /** TimelineResponse */
        TimelineResponse: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "hour" | "day" | "week";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Buckets */
            buckets: components["schemas"]["TimelineBucket"][];
        };
        /** ToolCallRecord */
        ToolCallRecord: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ViewSummary
         * @description Aggregate of the events matching a map view (bbox and filters).
         */
        ViewSummary: {
            /** Total */
            total: number;
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /** By Type */
            by_type: {
                [key: string]: number;
            };
            /** Affected Population */
            affected_population: number;
            /** Last Updated */
            last_updated: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                q?: string | null;
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                start_date?: string | null;
                end_date?: string | null;
                min_lng?: number | null;
                min_lat?: number | null;
                max_lng?: number | null;
                max_lat?: number | null;
                center_lat?: number | null;
                center_lng?: number | null;
                radius_km?: number | null;
                is_active?: boolean | null;
                /** @description Only events ongoing at this time */
                at?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_timeline_api_v1_events_timeline_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                bucket?: "hour" | "day" | "week";
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_layers_api_v1_events__event_id__layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vector_tile_api_v1_geodata_tiles__z___x___y__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_clusters_api_v1_geodata_events_clusters_get: {
        parameters: {
            query: {
                /** @description Map zoom level (0-20) */
                zoom: number;
                min_lat?: number | null;
                max_lat?: number | null;
                min_lng?: number | null;
                max_lng?: number | null;
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_geojson_api_v1_geodata_events_geojson_get: {
        parameters: {
            query?: {
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                start_date?: string | null;
                end_date?: string | null;
                min_lng?: number | null;
                min_lat?: number | null;
                max_lng?: number | null;
                max_lat?: number | null;
                is_active?: boolean | null;
                include_properties?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_summary_api_v1_geodata_summary_get: {
        parameters: {
            query?: {
                min_lng?: number | null;
                min_lat?: number | null;
                max_lng?: number | null;
                max_lat?: number | null;
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                /** @description Events ongoing at this time */
                at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nearby_events_api_v1_geodata_nearby_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius_km?: number;
                limit?: number;
                types?: components["schemas"]["EventType"][] | null;
                severities?: components["schemas"]["SeverityLevel"][] | null;
                /** @description Events ongoing at this time */
                at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_gdacs_api_v1_sync_gdacs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_copernicus_api_v1_sync_copernicus_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_usgs_api_v1_sync_usgs_post: {
        parameters: {
            query?: {
                /** @description USGS feed to sync. Options: 4.5_day, 4.5_week, all_day, significant_month */
                feed?: "4.5_day" | "4.5_week" | "all_day" | "significant_month";
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_eonet_api_v1_sync_eonet_post: {
        parameters: {
            query?: {
                /** @description Event status filter. Options: open, closed, all */
                status?: "open" | "closed" | "all";
                /** @description Fetch events from the last N days */
                days?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_status_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"][];
                };
            };
        };
    };
    active_cyclones_api_v1_hazards_cyclones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recent_shakemaps_api_v1_hazards_shakemaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    active_fires_api_v1_hazards_fires_get: {
        parameters: {
            query: {
                min_lng: number;
                min_lat: number;
                max_lng: number;
                max_lat: number;
                hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_status_api_v1_agent_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStatus"];
                };
            };
        };
    };
    agent_usage_api_v1_agent_usage_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_chat_api_v1_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satellite_positions_api_v1_tracks_satellites_get: {
        parameters: {
            query?: {
                /** @description Instant (default now) */
                at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satellite_passes_api_v1_tracks_satellites_passes_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                hours?: number;
                /** @description Degrees above the horizon */
                min_elevation?: number;
                /** @description Only passes useful to optical imagers */
                daylight_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatellitePassesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aircraft_around_api_v1_tracks_aircraft_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                /** @description Nautical miles */
                radius_nm?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vessels_in_view_api_v1_tracks_vessels_get: {
        parameters: {
            query: {
                min_lng: number;
                min_lat: number;
                max_lng: number;
                max_lat: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cameras_in_view_api_v1_cameras_get: {
        parameters: {
            query: {
                min_lng: number;
                min_lat: number;
                max_lng: number;
                max_lat: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cameras_nearby_api_v1_cameras_nearby_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius_km?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyCamera"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    camera_snapshot_api_v1_cameras__camera_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    radio_nearby_api_v1_radio_nearby_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius_km?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadioNearbyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_api_v1_routing_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    infrastructure_in_view_api_v1_infrastructure_get: {
        parameters: {
            query: {
                min_lng: number;
                min_lat: number;
                max_lng: number;
                max_lat: number;
                kinds?: ("dam" | "power_plant")[] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_status_api_v1_admin_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dedup_status_api_v1_admin_dedup_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_v1_admin_sync_trigger_post: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_offline_merge_api_v1_admin_merge_trigger_post: {
        parameters: {
            query?: {
                /** @description Preview without making changes */
                dry_run?: boolean;
                /** @description Scope: all, active, or inactive */
                scope?: string;
                /** @description Process events since date (ISO format) */
                since?: string | null;
                /** @description Comma-separated event types */
                types?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_merge_status_api_v1_admin_merge_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    scheduler_status_scheduler_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
