/**
 * This file is auto-generated by openapi-typescript.
 * Do not make direct changes to this file.
 *
 * Run `pnpm generate:types` to regenerate.
 *
 * @see https://openapi-ts.dev
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scheduler/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["scheduler_status_scheduler_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_events_api_v1_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events/{event_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_event_api_v1_events__event_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events/{event_id}/layers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_event_layers_api_v1_events__event_id__layers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/geodata/geojson": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_events_geojson_api_v1_geodata_geojson_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sync/gdacs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sync_gdacs_api_v1_sync_gdacs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sync/copernicus": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sync_copernicus_api_v1_sync_copernicus_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** DataSource */
    DataSource: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Type */
      type: "gdacs" | "copernicus" | "unosat" | "hdx" | "user";
      /** Url */
      url?: string | null;
    };
    /** Dataset */
    Dataset: {
      /** Id */
      id: string;
      /** Event Id */
      event_id: string;
      /** Name */
      name: string;
      /** Type */
      type: "satellite_image" | "vector" | "3d_tiles" | "report" | "other";
      /** Url */
      url?: string | null;
      /** License */
      license?: string | null;
      /** Metadata */
      metadata?: Record<string, unknown> | null;
    };
    /** DisasterEvent */
    DisasterEvent: {
      /** Id */
      id: string;
      /** Type */
      type:
        | "earthquake"
        | "flood"
        | "wildfire"
        | "hurricane"
        | "tsunami"
        | "volcano"
        | "war"
        | "pollution"
        | "drought"
        | "other";
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      location: components["schemas"]["Location"];
      /** Severity */
      severity: "low" | "medium" | "high" | "critical";
      /** Affected Population */
      affected_population?: number | null;
      /** Affected Area Km2 */
      affected_area_km2?: number | null;
      /**
       * Start Date
       * @format date-time
       */
      start_date: string;
      /**
       * End Date
       * @format date-time
       */
      end_date?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Sources */
      sources: components["schemas"]["DataSource"][];
      geometry?: components["schemas"]["GeoJSONGeometry"] | null;
      /**
       * Created At
       * @format date-time
       */
      created_at: string;
      /**
       * Updated At
       * @format date-time
       */
      updated_at: string;
    };
    /** DisasterEventDetail */
    DisasterEventDetail: {
      /** Id */
      id: string;
      /** Type */
      type:
        | "earthquake"
        | "flood"
        | "wildfire"
        | "hurricane"
        | "tsunami"
        | "volcano"
        | "war"
        | "pollution"
        | "drought"
        | "other";
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      location: components["schemas"]["Location"];
      /** Severity */
      severity: "low" | "medium" | "high" | "critical";
      /** Affected Population */
      affected_population?: number | null;
      /** Affected Area Km2 */
      affected_area_km2?: number | null;
      /**
       * Start Date
       * @format date-time
       */
      start_date: string;
      /**
       * End Date
       * @format date-time
       */
      end_date?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Sources */
      sources: components["schemas"]["DataSource"][];
      geometry?: components["schemas"]["GeoJSONGeometry"] | null;
      /**
       * Created At
       * @format date-time
       */
      created_at: string;
      /**
       * Updated At
       * @format date-time
       */
      updated_at: string;
      /** Layers */
      layers: components["schemas"]["GeoLayer"][];
      /** Datasets */
      datasets: components["schemas"]["Dataset"][];
      /** Metrics */
      metrics: components["schemas"]["EventMetric"][];
    };
    /** EventListResponse */
    EventListResponse: {
      /** Data */
      data: components["schemas"]["DisasterEvent"][];
      pagination: components["schemas"]["Pagination"];
    };
    /** EventMetric */
    EventMetric: {
      /**
       * Time
       * @format date-time
       */
      time: string;
      /** Event Id */
      event_id: string;
      /** Metric Type */
      metric_type: string;
      /** Value */
      value: number;
    };
    /** GeoJSONFeature */
    GeoJSONFeature: {
      /**
       * Type
       * @default Feature
       * @constant
       * @enum {string}
       */
      type: "Feature";
      geometry: components["schemas"]["GeoJSONGeometry"];
      /** Properties */
      properties: Record<string, unknown>;
      /** Id */
      id?: string | null;
    };
    /** GeoJSONFeatureCollection */
    GeoJSONFeatureCollection: {
      /**
       * Type
       * @default FeatureCollection
       * @constant
       * @enum {string}
       */
      type: "FeatureCollection";
      /** Features */
      features: components["schemas"]["GeoJSONFeature"][];
    };
    /**
     * GeoJSONGeometry
     * @description GeoJSON geometry types
     */
    GeoJSONGeometry:
      | components["schemas"]["GeoJSONPoint"]
      | components["schemas"]["GeoJSONPolygon"]
      | components["schemas"]["GeoJSONMultiPolygon"];
    /** GeoJSONMultiPolygon */
    GeoJSONMultiPolygon: {
      /**
       * Type
       * @default MultiPolygon
       * @constant
       * @enum {string}
       */
      type: "MultiPolygon";
      /** Coordinates */
      coordinates: number[][][][];
    };
    /** GeoJSONPoint */
    GeoJSONPoint: {
      /**
       * Type
       * @default Point
       * @constant
       * @enum {string}
       */
      type: "Point";
      /**
       * Coordinates
       * @description [longitude, latitude]
       */
      coordinates: [number, number];
    };
    /** GeoJSONPolygon */
    GeoJSONPolygon: {
      /**
       * Type
       * @default Polygon
       * @constant
       * @enum {string}
       */
      type: "Polygon";
      /** Coordinates */
      coordinates: number[][][];
    };
    /** GeoLayer */
    GeoLayer: {
      /** Id */
      id: string;
      /** Event Id */
      event_id: string;
      /** Layer Type */
      layer_type: string;
      geometry: components["schemas"]["GeoJSONGeometry"];
      /** Properties */
      properties: Record<string, unknown>;
      /**
       * Timestamp
       * @format date-time
       */
      timestamp?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Location */
    Location: {
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Country */
      country?: string | null;
      /** Country Code */
      country_code?: string | null;
      /** Region */
      region?: string | null;
    };
    /** Pagination */
    Pagination: {
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Has More */
      has_more: boolean;
    };
    /** SyncResponse */
    SyncResponse: {
      /** Message */
      message: string;
      /** Events Synced */
      events_synced: number;
      /** Events Updated */
      events_updated: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  scheduler_status_scheduler_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_events_api_v1_events_get: {
    parameters: {
      query?: {
        /** @description Filter by event types */
        types?: (
          | "earthquake"
          | "flood"
          | "wildfire"
          | "hurricane"
          | "tsunami"
          | "volcano"
          | "war"
          | "pollution"
          | "drought"
          | "other"
        )[];
        /** @description Filter by severity levels */
        severities?: ("low" | "medium" | "high" | "critical")[];
        /** @description Filter events starting from this date */
        start_date?: string | null;
        /** @description Filter events until this date */
        end_date?: string | null;
        /** @description Filter by active status */
        is_active?: boolean | null;
        /** @description Minimum longitude for bounding box */
        min_lng?: number | null;
        /** @description Minimum latitude for bounding box */
        min_lat?: number | null;
        /** @description Maximum longitude for bounding box */
        max_lng?: number | null;
        /** @description Maximum latitude for bounding box */
        max_lat?: number | null;
        /** @description Maximum number of results */
        limit?: number;
        /** @description Number of results to skip */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_event_api_v1_events__event_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DisasterEventDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_event_layers_api_v1_events__event_id__layers_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Layers */
            layers: components["schemas"]["GeoLayer"][];
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_events_geojson_api_v1_geodata_geojson_get: {
    parameters: {
      query?: {
        /** @description Filter by event types */
        types?: (
          | "earthquake"
          | "flood"
          | "wildfire"
          | "hurricane"
          | "tsunami"
          | "volcano"
          | "war"
          | "pollution"
          | "drought"
          | "other"
        )[];
        /** @description Filter by severity levels */
        severities?: ("low" | "medium" | "high" | "critical")[];
        /** @description Filter events starting from this date */
        start_date?: string | null;
        /** @description Filter events until this date */
        end_date?: string | null;
        /** @description Filter by active status */
        is_active?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GeoJSONFeatureCollection"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_gdacs_api_v1_sync_gdacs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncResponse"];
        };
      };
    };
  };
  sync_copernicus_api_v1_sync_copernicus_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncResponse"];
        };
      };
    };
  };
}
